export const CAROUSEL_ITEM_REQUEST_STARTED = 'CAROUSEL_ITEM_REQUEST_STARTED';
export const CAROUSEL_ITEM_REQUEST_FINISHED = 'CAROUSEL_ITEM_REQUEST_FINISHED';
export const CAROUSEL_ITEM_ERROR = 'CAROUSEL_ITEM_ERROR';
