export const MOVIES_COLLECTION_REQUEST_STARTED = 'MOVIES_COLLECTION_REQUEST_STARTED';
export const MOVIES_COLLECTION_REQUEST_SUCCESS = 'MOVIES_COLLECTION_REQUEST_SUCCESS';
export const MOVIES_COLLECTION_REQUEST_ERROR = 'MOVIES_COLLECTION_REQUEST_ERROR';
